[cursor]
style = "Block"

[font]
size = 22.0
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
offset = { x = -1, y = 1 }

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 0 
y = 0 

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.95
blur = false

[shell]
program = "zsh"
args = ["-l"]

[colors]
cursor = { text = "#404040", cursor = "#f3fef0" }
transparent_background_colors = true

[colors.primary]
background = "#1C1D1D"

[mouse]
bindings = [
   { mouse = "Right", mods = "Control", action = "Paste" },
]
